
package com.bernardomg.tabletop.dice.roll;

import com.bernardomg.tabletop.dice.Dice;
import com.bernardomg.tabletop.dice.history.RollResult;

public interface RollGenerator {

    /**
     * Returns the value from a dice.
     * <p>
     * This will generate a random value for each die in the dice set. The
     * actual random value will be generated by the dice roller.
     * 
     * @param dice
     *            dice to roll
     * @return result from rolling the dice
     */
    public RollResult roll(final Dice dice);

}
