/**
 * Copyright 2014-2016 the original author or authors
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package com.wandrell.tabletop.dice.test.unit.roller;

import java.util.Collection;
import java.util.Iterator;

import org.mockito.Matchers;
import org.mockito.Mockito;
import org.testng.Assert;
import org.testng.annotations.Test;

import com.wandrell.tabletop.dice.Dice;
import com.wandrell.tabletop.dice.roller.DefaultRoller;
import com.wandrell.tabletop.dice.roller.Roller;
import com.wandrell.tabletop.dice.roller.random.NumberGenerator;

/**
 * Units tests for {@code DefaultRoller}, checking that it returns values as
 * expected.
 * <p>
 * Checks the following cases:
 * <ol>
 * <li>The roller returns the values generated by its number generator.</li>
 * <li>The roller returns as many values as the quantity of dice.</li>
 * </ol>
 * 
 * @author Bernardo Martínez Garrido
 */
public final class TestDefaultRoller {

    /**
     * Default constructor.
     */
    public TestDefaultRoller() {
        super();
    }

    /**
     * Tests that the roller returns as many values as the quantity of dice.
     */
    @Test
    public final void testRoll_ResultsSize() {
        final Dice dice;     // Mocked dice
        final Roller roller; // Tested roller

        // Mocks dice
        dice = Mockito.mock(Dice.class);
        Mockito.when(dice.getQuantity()).thenReturn(10);
        Mockito.when(dice.getSides()).thenReturn(6);

        // Initializes roller
        roller = new DefaultRoller();

        Assert.assertEquals(roller.roll(dice).size(), 10);
    }

    /**
     * Tests that the roller returns the values generated by its number
     * generator.
     */
    @Test
    public final void testRoll_ReturnsGenerated() {
        final Roller roller;                // Roller being tested
        final Dice dice;                    // Die to roll
        final NumberGenerator generator;    // Number generator used
        final Collection<Integer> result;   // Roll results
        final Iterator<Integer> itrInteger; // Results iterator

        // Mocks dice
        dice = Mockito.mock(Dice.class);
        Mockito.when(dice.getQuantity()).thenReturn(3);
        Mockito.when(dice.getSides()).thenReturn(6);

        // Mocks generator
        generator = Mockito.mock(NumberGenerator.class);
        Mockito.when(generator.generate(Matchers.anyInt())).thenReturn(3, 5, 1);

        // Initializes roller
        roller = new DefaultRoller(generator);

        // Rolls dice
        result = roller.roll(dice);
        itrInteger = result.iterator();

        Assert.assertEquals(itrInteger.next(), (Integer) 3);
        Assert.assertEquals(itrInteger.next(), (Integer) 5);
        Assert.assertEquals(itrInteger.next(), (Integer) 1);
    }

}
