/**
 * Copyright 2014-2019 the original author or authors
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package com.bernardomg.tabletop.dice.test.unit.roll;

import java.util.Arrays;
import java.util.Iterator;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.platform.runner.JUnitPlatform;
import org.junit.runner.RunWith;
import org.mockito.ArgumentMatchers;
import org.mockito.Mockito;

import com.bernardomg.tabletop.dice.Dice;
import com.bernardomg.tabletop.dice.random.DiceToRollResult;
import com.bernardomg.tabletop.dice.random.NumberGenerator;

/**
 * Units tests for {@link DiceToRollResult}, verifying that it generates values
 * as expected.
 * 
 * @author Bernardo Mart&iacute;nez Garrido
 */
@RunWith(JUnitPlatform.class)
public final class TestDiceToRollResult {

    /**
     * Default constructor.
     */
    public TestDiceToRollResult() {
        super();
    }

    /**
     * Verifies that the roller returns all the rolls generated by the
     * generator.
     */
    @Test
    public final void testApply_ReturnsAllRolls() {
        final Dice dice;
        final Iterator<Integer> rolled;
        final NumberGenerator generator;

        // Mocks dice
        dice = Mockito.mock(Dice.class);
        Mockito.when(dice.getQuantity()).thenReturn(2);
        Mockito.when(dice.getSides()).thenReturn(1);

        // Mocks generator
        generator = Mockito.mock(NumberGenerator.class);
        Mockito.when(generator.generate((Dice) ArgumentMatchers.any()))
                .thenReturn(Arrays.asList(1, 2));

        rolled = new DiceToRollResult(generator).apply(dice).getAllRolls()
                .iterator();

        Assertions.assertEquals(new Integer(1), rolled.next());
        Assertions.assertEquals(new Integer(2), rolled.next());
    }

    /**
     * Verifies that the roller returns the total roll as a sum of all the
     * generated values.
     */
    @Test
    public final void testApply_AddsTotalRoll() {
        final Dice dice;
        final Integer rolled;
        final NumberGenerator generator;

        // Mocks dice
        dice = Mockito.mock(Dice.class);
        Mockito.when(dice.getQuantity()).thenReturn(3);
        Mockito.when(dice.getSides()).thenReturn(1);

        // Mocks generator
        generator = Mockito.mock(NumberGenerator.class);
        Mockito.when(generator.generate((Dice) ArgumentMatchers.any()))
                .thenReturn(Arrays.asList(1, 2, 3));

        rolled = new DiceToRollResult(generator).apply(dice).getTotalRoll();

        Assertions.assertEquals(new Integer(6), rolled);
    }

    /**
     * Verifies that the roller returns the total roll when there is a single
     * value.
     */
    @Test
    public final void testApply_AddSingleValue() {
        final Dice dice;
        final Integer rolled;
        final NumberGenerator generator;

        // Mocks dice
        dice = Mockito.mock(Dice.class);
        Mockito.when(dice.getQuantity()).thenReturn(1);
        Mockito.when(dice.getSides()).thenReturn(1);

        // Mocks generator
        generator = Mockito.mock(NumberGenerator.class);
        Mockito.when(generator.generate((Dice) ArgumentMatchers.any()))
                .thenReturn(Arrays.asList(5));

        rolled = new DiceToRollResult(generator).apply(dice).getTotalRoll();

        Assertions.assertEquals(new Integer(5), rolled);
    }

    /**
     * Verifies that the roller returns the total roll when there is a single
     * value.
     */
    @Test
    public final void testApply_ReturnsDice() {
        final Dice dice;
        final NumberGenerator generator;
        final Dice returned;

        // Mocks dice
        dice = Mockito.mock(Dice.class);
        Mockito.when(dice.getQuantity()).thenReturn(1);
        Mockito.when(dice.getSides()).thenReturn(2);

        // Mocks generator
        generator = Mockito.mock(NumberGenerator.class);
        Mockito.when(generator.generate((Dice) ArgumentMatchers.any()))
                .thenReturn(Arrays.asList(5));

        returned = new DiceToRollResult(generator).apply(dice).getDice();

        Assertions.assertEquals(new Integer(1), returned.getQuantity());
        Assertions.assertEquals(new Integer(2), returned.getSides());
    }

}
