/**
 * Copyright 2014-2019 the original author or authors
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package com.bernardomg.tabletop.dice.transformer;

import static com.google.common.base.Preconditions.checkNotNull;

import java.util.ArrayList;
import java.util.Collection;
import java.util.function.BiFunction;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.bernardomg.tabletop.dice.Dice;
import com.bernardomg.tabletop.dice.notation.DiceNotationExpression;
import com.bernardomg.tabletop.dice.notation.operand.ConstantOperand;
import com.bernardomg.tabletop.dice.notation.operand.DiceOperand;
import com.bernardomg.tabletop.dice.notation.operation.BinaryOperation;
import com.bernardomg.tabletop.dice.random.NumberGenerator;
import com.bernardomg.tabletop.dice.random.RandomNumberGenerator;

/**
 * Dice notation expression which simulates rolling the expression.
 * <p>
 * As some values, such as dice, represent random numbers the transformer may
 * not return the same result each time it is executed for the same expression.
 * <p>
 * The random value will be generated by a {@link NumberGenerator} contained in
 * the transformer, which can be set through the constructor. Otherwise the
 * default one, a {@link RandomNumberGenerator}, will be used.
 * 
 * @author Bernardo Mart&iacute;nez Garrido
 *
 */
public final class DiceRoller implements DiceInterpreter<Integer> {

    /**
     * Logger.
     */
    private static final Logger   LOGGER = LoggerFactory
            .getLogger(DiceRoller.class);

    /**
     * The random numbers generator.
     * <p>
     * Combined with the data in the rolled this, this will generate a random
     * value in an interval.
     */
    private final NumberGenerator numberGenerator;

    /**
     * Default constructor.
     */
    public DiceRoller() {
        super();

        numberGenerator = new RandomNumberGenerator();
    }

    /**
     * Constructs a transformer using the received roller for simulating rolls.
     * 
     * @param generator
     *            the random number generator to use
     */
    public DiceRoller(final NumberGenerator generator) {
        super();

        numberGenerator = checkNotNull(generator,
                "Received a null pointer as generator");
    }

    @Override
    public final Integer transform(final DiceNotationExpression expression) {
        final Integer result;

        // TODO: Try iterating instead of recursions
        LOGGER.debug("Transforming expression {}", expression.getClass());
        if (expression instanceof BinaryOperation) {
            result = transform((BinaryOperation) expression);
        } else if (expression instanceof ConstantOperand) {
            result = transform((ConstantOperand) expression);
        } else if (expression instanceof DiceOperand) {
            result = transform((DiceOperand) expression);
        } else {
            LOGGER.warn("Unsupported expression");
            result = 0;
        }

        return result;
    }

    /**
     * Generates a collection of random values from the received {@code Dice}.
     * <p>
     * These are returned in the same order they were generated.
     * 
     * @param dice
     *            the dice to roll
     * @return a collection of random values generated from the dice
     */
    private final Iterable<Integer> roll(final Dice dice) {
        final Collection<Integer> rolls; // Roll results
        final Integer quantity;
        final Boolean negative;

        checkNotNull(dice, "Received a null pointer as dice");

        if (dice.getQuantity() < 0) {
            quantity = 0 - dice.getQuantity();
            negative = true;
        } else {
            quantity = dice.getQuantity();
            negative = false;
        }

        rolls = new ArrayList<Integer>();
        for (Integer i = 0; i < quantity; i++) {
            if (negative) {
                rolls.add(0 - numberGenerator.generate(dice.getSides()));
            } else {
                rolls.add(numberGenerator.generate(dice.getSides()));
            }
        }

        return rolls;
    }

    /**
     * Generates a random value from a binary operation.
     * <p>
     * It generates a value for both sides of the operation, then applies the
     * operation to these values.
     * 
     * @param operation
     *            operation to transform
     * @return a random value generated from the operation
     */
    private final Integer transform(final BinaryOperation operation) {
        final DiceNotationExpression left;
        final DiceNotationExpression right;
        final Integer leftValue;
        final Integer rightValue;
        final Integer value;
        final BiFunction<Integer, Integer, Integer> func;

        left = operation.getLeft();
        right = operation.getRight();

        func = operation.getOperation();

        LOGGER.debug("Transforming left operand");
        leftValue = transform(left);
        LOGGER.debug("Transforming right operand");
        rightValue = transform(right);

        value = func.apply(leftValue, rightValue);

        return value;
    }

    /**
     * Returns the value from a constant operand.
     * 
     * @param operand
     *            operand to transform
     * @return the constant from the operand
     */
    private final Integer transform(final ConstantOperand operand) {
        return operand.getValue();
    }

    /**
     * Returns the value from a dice operand.
     * <p>
     * This will generate a random value for each die in the dice set. The
     * actual random value will be generated by the dice roller.
     * 
     * @param operand
     *            operand to transform
     * @return a random value generated from the dice
     */
    private final Integer transform(final DiceOperand operand) {
        final Iterable<Integer> rolls;
        Integer total;

        rolls = roll(operand.getDice());

        total = 0;
        for (final Integer roll : rolls) {
            total += roll;
        }

        return total;
    }

}
